apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
    spec:
      containers:
      - name: django-app
        image: your_dockerhub_username/messaging_app:latest  
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mysql://$(DB_USER):$(DB_PASSWORD)@db/$(DB_NAME)"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: django-messaging-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: django-messaging-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-messaging-config
              key: DB_PASSWORD
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: django-messaging-config
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: django-messaging-config
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-messaging-config
              key: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-messaging-config
              key: DB_PASSWORD
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  type: ClusterIP
  selector:
    app: django-messaging-app
  ports:
    - port: 8000
      targetPort: 8000