pipeline {
    agent any

    tools {
        // Requires ShiningPanda plugin for Python virtualenv
        python 'Python3'
    }

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-alx-backend',  // Replace with Jenkins credentials ID
                    url: 'https://github.com/Reaganz-Wat/alx-backend-python.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                '''
            }
        }

        stage('Install Dependecies') {
            steps {
                sh '''
                pip install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    python3 manage.py test chats/tests.py --verbosity=2
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/report.xml', fingerprint: true
        }
    }
}
